scrape_configs:
      - job_name: 'prometheus'
        static_configs:
         - targets: ['localhost:9090']
      - job_name: 'springtomcat'
        static_configs:
         - targets: ['springtomcat:9300']